export App from './App'
export Home from './Home'
export Pages from './Pages/Index'
export ShowPage from './Pages/Show'
export PageForm from './Pages/Form'
export MenuIcon from './Menu'
export POSPages from './POSPages'
export CustomerInfo from './CustomerInfo'