export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST'
export const LOAD_PAGES_SUCCESS = 'LOAD_PAGES_SUCCESS'
export const LOAD_PAGES_FAILURE = 'LOAD_PAGES_FAILURE'

export const LOAD_PAGE_REQUEST = 'LOAD_PAGE_REQUEST'
export const LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS'
export const LOAD_PAGE_FAILURE = 'LOAD_PAGE_FAILURE'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const NAV_MENU_CLICK = 'NAV_MENU_CLICK'

//MASTER_PROVINCE
export const LOAD_MASTER_PROVINCE_REQUEST = 'LOAD_MASTER_PROVINCE_REQUEST'
export const LOAD_MASTER_PROVINCE_SUCCESS = 'LOAD_MASTER_PROVINCE_SUCCESS'
export const LOAD_MASTER_PROVINCE_FAILURE = 'LOAD_MASTER_PROVINCE_FAILURE'
//MASTER_AMPHUR
export const LOAD_MASTER_AMPHUR_REQUEST = 'LOAD_MASTER_AMPHUR_REQUEST'
export const LOAD_MASTER_AMPHUR_SUCCESS = 'LOAD_MASTER_AMPHUR_SUCCESS'
export const LOAD_MASTER_AMPHUR_FAILURE = 'LOAD_MASTER_AMPHUR_FAILURE'
//MASTER_DISTRICT
export const LOAD_MASTER_DISTRICT_REQUEST = 'LOAD_MASTER_DISTRICT_REQUEST'
export const LOAD_MASTER_DISTRICT_SUCCESS = 'LOAD_MASTER_DISTRICT_SUCCESS'
export const LOAD_MASTER_DISTRICT_FAILURE = 'LOAD_MASTER_DISTRICT_FAILURE'
//MASTER_SOURCT_TYPE
export const LOAD_MASTER_SOURCE_TYPE_REQUEST = 'LOAD_MASTER_SOURCE_TYPE_REQUEST'
export const LOAD_MASTER_SOURCE_TYPE_SUCCESS = 'LOAD_MASTER_SOURCE_TYPE_SUCCESS'
export const LOAD_MASTER_SOURCE_TYPE_FAILURE = 'LOAD_MASTER_SOURCE_TYPE_FAILURE'
//MASTER_CHANNEL_TYPE
export const LOAD_MASTER_CHANNEL_TYPE_REQUEST = 'LOAD_MASTER_CHANNEL_TYPE_REQUEST'
export const LOAD_MASTER_CHANNEL_TYPE_SUCCESS = 'LOAD_MASTER_CHANNEL_TYPE_SUCCESS'
export const LOAD_MASTER_CHANNEL_TYPE_FAILURE = 'LOAD_MASTER_CHANNEL_TYPE_FAILURE'
//MASTER_BUSINESS_TYPE
export const LOAD_MASTER_BUSINESS_TYPE_REQUEST = 'LOAD_MASTER_BUSINESS_TYPE_REQUEST'
export const LOAD_MASTER_BUSINESS_TYPE_SUCCESS = 'LOAD_MASTER_BUSINESS_TYPE_SUCCESS'
export const LOAD_MASTER_BUSINESS_TYPE_FAILURE = 'LOAD_MASTER_BUSINESS_TYPE_FAILURE'
//MASTER_INTERESTING_PRODUCT
export const LOAD_MASTER_INTERESTING_PRODUCT_REQUEST = 'LOAD_MASTER_INTERESTING_PRODUCT_REQUEST'
export const LOAD_MASTER_INTERESTING_PRODUCT_SUCCESS = 'LOAD_MASTER_INTERESTING_PRODUCT_SUCCESS'
export const LOAD_MASTER_INTERESTING_PRODUCT_FAILURE = 'LOAD_MASTER_INTERESTING_PRODUCT_FAILURE'
//MASTER_OPPORTUNITY_CUSTOMER
export const LOAD_MASTER_OPPORTUNITY_CUSTOMER_REQUEST = 'LOAD_MASTER_OPPORTUNITY_CUSTOMER_REQUEST'
export const LOAD_MASTER_OPPORTUNITY_CUSTOMER_SUCCESS = 'LOAD_MASTER_OPPORTUNITY_CUSTOMER_SUCCESS'
export const LOAD_MASTER_OPPORTUNITY_CUSTOMER_FAILURE = 'LOAD_MASTER_OPPORTUNITY_CUSTOMER_FAILURE'
//MASTER_PRESENT_PRODUCT_TYPE
export const LOAD_MASTER_PRESENT_PRODUCT_TYPE_REQUEST = 'LOAD_MASTER_PRESENT_PRODUCT_TYPE_REQUEST'
export const LOAD_MASTER_PRESENT_PRODUCT_TYPE_SUCCESS = 'LOAD_MASTER_PRESENT_PRODUCT_TYPE_SUCCESS'
export const LOAD_MASTER_PRESENT_PRODUCT_TYPE_FAILURE = 'LOAD_MASTER_PRESENT_PRODUCT_TYPE_FAILURE'
//MASTER_BUSINESS_PREFIX
export const LOAD_MASTER_BUSINESS_PREFIX_REQUEST = 'LOAD_MASTER_BUSINESS_PREFIX_REQUEST'
export const LOAD_MASTER_BUSINESS_PREFIX_SUCCESS = 'LOAD_MASTER_BUSINESS_PREFIX_SUCCESS'
export const LOAD_MASTER_BUSINESS_PREFIX_FAILURE = 'LOAD_MASTER_BUSINESS_PREFIX_FAILURE'
//MASTER_APPOINTMENT_REASON
export const LOAD_MASTER_APPOINTMENT_REASON_REQUEST = 'LOAD_MASTER_APPOINTMENT_REASON_REQUEST'
export const LOAD_MASTER_APPOINTMENT_REASON_SUCCESS = 'LOAD_MASTER_APPOINTMENT_REASON_SUCCESS'
export const LOAD_MASTER_APPOINTMENT_REASON_FAILURE = 'LOAD_MASTER_APPOINTMENT_REASON_FAILURE'

