import { CALL_API } from 'redux-api-middleware'

import {
    MASTER_PROVINCE,
    MASTER_AMPHUR,
    MASTER_DISTRICT,
    MASTER_SOURCE_TYPE,
    MASTER_CHANNEL_TYPE,
    MASTER_BUSINESS_TYPE,
    MASTER_INTERESTING_PRODUCT,
    MASTER_OPPORTUNITY_CUSTOMER,
    MASTER_PRESENT_PRODUCT_TYPE,
    MASTER_BUSINESS_PREFIX,
    MASTER_APPOINTMENT_REASON
} from '../constants/endpoints'

import {
    //MASTER_PROVINCE
    LOAD_MASTER_PROVINCE_REQUEST,
    LOAD_MASTER_PROVINCE_SUCCESS,
    LOAD_MASTER_PROVINCE_FAILURE,

    //MASTER_AMPHUR
    LOAD_MASTER_AMPHUR_REQUEST,
    LOAD_MASTER_AMPHUR_SUCCESS,
    LOAD_MASTER_AMPHUR_FAILURE,

    //MASTER_DISTRICT
    LOAD_MASTER_DISTRICT_REQUEST,
    LOAD_MASTER_DISTRICT_SUCCESS,
    LOAD_MASTER_DISTRICT_FAILURE,

    //MASTER_SOURCE_TYPE
    LOAD_MASTER_SOURCE_TYPE_REQUEST,
    LOAD_MASTER_SOURCE_TYPE_SUCCESS,
    LOAD_MASTER_SOURCE_TYPE_FAILURE,

    //MASTER_CHANNEL_TYPE
    LOAD_MASTER_CHANNEL_TYPE_REQUEST,
    LOAD_MASTER_CHANNEL_TYPE_SUCCESS,
    LOAD_MASTER_CHANNEL_TYPE_FAILURE,

    //MASTER_BUSINESS_TYPE
    LOAD_MASTER_BUSINESS_TYPE_REQUEST,
    LOAD_MASTER_BUSINESS_TYPE_SUCCESS,
    LOAD_MASTER_BUSINESS_TYPE_FAILURE,

    //MASTER_INTERESTING_PRODUCT
    LOAD_MASTER_INTERESTING_PRODUCT_REQUEST,
    LOAD_MASTER_INTERESTING_PRODUCT_SUCCESS,
    LOAD_MASTER_INTERESTING_PRODUCT_FAILURE,

    //MASTER_OPPORTUNITY_CUSTOMER
    LOAD_MASTER_OPPORTUNITY_CUSTOMER_REQUEST,
    LOAD_MASTER_OPPORTUNITY_CUSTOMER_SUCCESS,
    LOAD_MASTER_OPPORTUNITY_CUSTOMER_FAILURE,

    //MASTER_PRESENT_PRODUCT_TYPE
    LOAD_MASTER_PRESENT_PRODUCT_TYPE_REQUEST,
    LOAD_MASTER_PRESENT_PRODUCT_TYPE_SUCCESS,
    LOAD_MASTER_PRESENT_PRODUCT_TYPE_FAILURE,

    //MASTER_BUSINESS_PREFIX
    LOAD_MASTER_BUSINESS_PREFIX_REQUEST,
    LOAD_MASTER_BUSINESS_PREFIX_SUCCESS,
    LOAD_MASTER_BUSINESS_PREFIX_FAILURE,

    //MASTER_APPOINTMENT_REASON
    LOAD_MASTER_APPOINTMENT_REASON_REQUEST,
    LOAD_MASTER_APPOINTMENT_REASON_SUCCESS,
    LOAD_MASTER_APPOINTMENT_REASON_FAILURE
} from '../constants/actionTypes'

export const getMasterProvince = () => {
    console.log(MASTER_PROVINCE)
    return ({
        [CALL_API]: {
            endpoint: MASTER_PROVINCE,
            method: 'GET',
            types: [LOAD_MASTER_PROVINCE_REQUEST, LOAD_MASTER_PROVINCE_SUCCESS, LOAD_MASTER_PROVINCE_FAILURE]
        }
    })
}

export const getMasterAmphur = () => ({
    [CALL_API]: {
        endpoint: MASTER_AMPHUR,
        method: 'GET',
        types: [LOAD_MASTER_AMPHUR_REQUEST, LOAD_MASTER_AMPHUR_SUCCESS, LOAD_MASTER_AMPHUR_FAILURE]
    }
})

export const getMasterDistrict = () => ({
    [CALL_API]: {
        endpoint: MASTER_DISTRICT,
        method: 'GET',
        types: [LOAD_MASTER_DISTRICT_REQUEST, LOAD_MASTER_DISTRICT_SUCCESS, LOAD_MASTER_DISTRICT_FAILURE]
    }
})

export const getMasterSourceType = () => ({
    [CALL_API]: {
        endpoint: MASTER_SOURCE_TYPE,
        method: 'GET',
        types: [LOAD_MASTER_SOURCE_TYPE_REQUEST, LOAD_MASTER_SOURCE_TYPE_SUCCESS, LOAD_MASTER_SOURCE_TYPE_FAILURE]
    }
})

export const getMasterChannelType = () => ({
    [CALL_API]: {
        endpoint: MASTER_CHANNEL_TYPE,
        method: 'GET',
        types: [LOAD_MASTER_CHANNEL_TYPE_REQUEST, LOAD_MASTER_CHANNEL_TYPE_SUCCESS, LOAD_MASTER_CHANNEL_TYPE_FAILURE]
    }
})

export const getMasterBusinessType = () => ({
    [CALL_API]: {
        endpoint: MASTER_BUSINESS_TYPE,
        method: 'GET',
        types: [LOAD_MASTER_BUSINESS_TYPE_REQUEST, LOAD_MASTER_BUSINESS_TYPE_SUCCESS, LOAD_MASTER_BUSINESS_TYPE_FAILURE]
    }
})

export const getMasterInterestingProduct = () => ({
    [CALL_API]: {
        endpoint: MASTER_INTERESTING_PRODUCT,
        method: 'GET',
        types: [LOAD_MASTER_INTERESTING_PRODUCT_REQUEST, LOAD_MASTER_INTERESTING_PRODUCT_SUCCESS, LOAD_MASTER_INTERESTING_PRODUCT_FAILURE]
    }
})

export const getMasterOpportunityCustomer = () => ({
    [CALL_API]: {
        endpoint: MASTER_OPPORTUNITY_CUSTOMER,
        method: 'GET',
        types: [LOAD_MASTER_OPPORTUNITY_CUSTOMER_REQUEST, LOAD_MASTER_OPPORTUNITY_CUSTOMER_SUCCESS, LOAD_MASTER_OPPORTUNITY_CUSTOMER_FAILURE]
    }
})

export const getMasterPresentProductType = () => ({
    [CALL_API]: {
        endpoint: MASTER_PRESENT_PRODUCT_TYPE,
        method: 'GET',
        types: [LOAD_MASTER_PRESENT_PRODUCT_TYPE_REQUEST, LOAD_MASTER_PRESENT_PRODUCT_TYPE_SUCCESS, LOAD_MASTER_PRESENT_PRODUCT_TYPE_FAILURE]
    }
})

export const getMasterBusinessPrefix = () => ({
    [CALL_API]: {
        endpoint: MASTER_BUSINESS_PREFIX,
        method: 'GET',
        types: [LOAD_MASTER_BUSINESS_PREFIX_REQUEST, LOAD_MASTER_BUSINESS_PREFIX_SUCCESS, LOAD_MASTER_BUSINESS_PREFIX_FAILURE]
    }
})

export const getMasterAppointmentReason = () => ({
    [CALL_API]: {
        endpoint: MASTER_APPOINTMENT_REASON,
        method: 'GET',
        types: [LOAD_MASTER_APPOINTMENT_REASON_REQUEST, LOAD_MASTER_APPOINTMENT_REASON_SUCCESS, LOAD_MASTER_APPOINTMENT_REASON_FAILURE]
    }
})
